included:
  - Sources
  - Tests
excluded:
  - Pods
  - .build
  - DerivedData

line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 25

reporter: "xcode" 